[tools]
rbxcloud = { github = "Sleitnick/rbx-cloud-cli", version = "x" }
rojo = { source = "rojo-rbx/rojo", version = "x" }
run-in-roblox = {source = "rojo-rbx/run-in-roblox", version = "=0.3.0"}
selene = { source = "Kampfkarren/selene", version = "x" }
wally = { source = "UpliftGames/wally", version = "x" }