[tools]
rbxcloud = { github = "Sleitnick/rbx-cloud-cli", version = "x" }
rojo = { source = "rojo-rbx/rojo", version = "x" }
selene = { source = "Kampfkarren/selene", version = "x" }
wally = { source = "UpliftGames/wally", version = "x" }