[tools]
rbxcloud = { github = "Sleitnick/rbx-cloud-cli", version = "=0.1.0-alpha.4" }
rojo = { source = "rojo-rbx/rojo", version = "=7.2.0" }
run-in-roblox = {source = "rojo-rbx/run-in-roblox", version = "=0.3.0"}
selene = { source = "Kampfkarren/selene", version = "x" }
wally = { source = "UpliftGames/wally", version = "=0.3.1" }