title = "ROBLOX-Git-Test"
gitRepoUrl = "https://github.com/Eyryse/ROBLOX-Git-Test"
gitSourceBranch = "master"

changelog = true

classOrder = []

[docusaurus]
onBrokenLinks = "warn"
onBrokenMarkdownLinks = "warn"
favicon = "/"

[home]
enabled = true
includeReadme = true

[footer]
style = "dark"
copyright = "Copyright © 2022 Eyryse. Built with Moonwave and Docusaurus"